# v0 - Unaudited: This is an initial version that has not yet been formally audited.
# A fully audited version will be published as a subsequent release.
# Use in production at your own risk.

module = "gno.land/r/nt/commondao/v0"
gno = "0.9"

[addpkg]
  creator = "g15ge0ae9077eh40erwrn2eq0xw6wupwqthpv34l"
