# v0 - Unaudited: This is an initial version that has not yet been formally audited.
# A fully audited version will be published as a subsequent release.
# Use in production at your own risk.

module = "gno.land/p/nt/ownable/v0/exts/authorizable"
gno = "0.9"
