name: autocounterd

on:
  push:
    paths:
      - misc/autocounterd
      - .github/workflows/autocounterd.yml
    branches:
      - "master"
      - "misc/autocounterd"
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  autocounterd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata autcounterd
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/autcounterd
          tags: |
            type=raw,value=latest
            type=semver,pattern=v{{version}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./misc/autocounterd
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
