name: build
on: [push, pull_request]

jobs:
  native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: build
        run: make
      - uses: actions/upload-artifact@v2
        with:
          name: gno
          path: github.com/gnolang



  omni:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: build
        run: make omni
      - uses: actions/upload-artifact@v2
        with:
          name: gno
          path: github.com/gnolang
          
          
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: build
        run: make test
