name: DB Tests

on:
  pull_request:
    paths:
      - "pkgs/db"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/db-tests.yml"
  push:
    branches:
      - master

jobs:
  test-databases:
    name: basic database test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        goversion: ["1.21.x", "1.22.x"]
        tags:
          - cleveldb
          - memdb
          - fsdb
          - boltdb
    steps:
      # golang
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      # leveldb
      - name: install leveldb
        if: ${{ matrix.tags=='cleveldb' }}
        run: |
          sudo apt-get install libsnappy1v5
          mkdir -p /tmp/leveldb
          cd /tmp/leveldb
          wget http://ftp.us.debian.org/debian/pool/main/l/leveldb/libleveldb1d_1.22-3_amd64.deb
          wget http://ftp.us.debian.org/debian/pool/main/l/leveldb/libleveldb-dev_1.22-3_amd64.deb
          sudo dpkg -i *.deb

      # test ./pkgs/db
      - uses: actions/checkout@v3
      - name: test ./pkgs/db
        run: go test -tags ${{ matrix.tags }} ./pkgs/db/...
