name: db-tests

on:
  pull_request:
    paths:
      - "tm2/pkg/db/**.go"
      - "go.sum"
      - ".github/workflows/db-tests.yml"
  push:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        goversion:
          - "1.21.x"
          - "1.22.x"
        tags:
          - cleveldb
          - memdb
          - fsdb
          - boltdb
    steps:
      - uses: actions/checkout@v4

      # golang
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.goversion }}

      # leveldb
      - name: install leveldb
        if: ${{ matrix.tags=='cleveldb' }}
        run: |
          sudo apt-get install libsnappy1v5
          mkdir -p /tmp/leveldb
          cd /tmp/leveldb
          wget http://ftp.us.debian.org/debian/pool/main/l/leveldb/libleveldb1d_1.22-3_amd64.deb
          wget http://ftp.us.debian.org/debian/pool/main/l/leveldb/libleveldb-dev_1.22-3_amd64.deb
          sudo dpkg -i *.deb

      - name: Set environment variables for debug mode
        if: env.ACTIONS_STEP_DEBUG == 'true'
        run: |
          export LOG_PATH_DIR=${{ runner.temp }}/logs
          mkdir -p $LOG_PATH_DIR

          echo "LOG_LEVEL=debug" >> $GITHUB_ENV
          echo "LOG_PATH_DIR=$LOG_PATH_DIR" >> $GITHUB_ENV
          
      # test ./pkgs/db
      - name: test ./tm2/pkg/db
        run: go test -tags ${{ matrix.tags }} ./tm2/pkg/db/...
