name: Dependency License Scanning

on:
  push:
    branches:
      - master
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  pull_request_target:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fossa:
    name: Fossa
    runs-on: ubuntu-latest
    if: github.repository == 'gnolang/gno'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Move .fossa.yml to root dir
        run: mv .github/.fossa.yml .

      - name: Cache Coursier cache
        uses: coursier/cache-action@v8.0.0

      - name: Set up JDK 17
        uses: coursier/setup-action@v2.0.2
        with:
          jvm: temurin:1.17

      - name: Set up fossa CLI
        run: "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash"

      - name: FOSSA analyze
        run: fossa analyze
        env:
          FOSSA_API_KEY: "${{secrets.FOSSA_API_KEY}}"

      - name: FOSSA test
        run: fossa test
        env:
          FOSSA_API_KEY: "${{secrets.FOSSA_API_KEY}}"
