# TODO: Add target OS
name: logos
on: [push, pull_request]

jobs:
  realm:
    strategy:
      matrix:
        build-os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64, riscv64]
    runs-on: ${{ matrix.build-os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: logos
        env:
          GOARCH ${{ matrix.arch }}
        run: |
          go mod download
          cd logos/cmd
          go build .
          
