name: logos
on: [push, pull_request]

jobs:
  goscan:
    strategy:
      fail-fast: false
      matrix:
        build-os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.build-os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: goscan
        run: make goscan
