name: portal-loop

on:
  push:
    paths:
      - misc/loop
      - .github/workflows/portal-loop.yml
    branches:
      - "master"
      - "ops/portal-loop"
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  portal-loop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata portalloopd
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/portalloopd
          tags: |
            type=raw,value=latest
            type=semver,pattern=v{{version}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./misc/loop
          target: portalloopd
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
