name: Stale PR Bot
on:
  schedule:
    - cron: "30 1 * * *"
permissions:
  pull-requests: write
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          # actions/stale's cache mechanism doesn't work if you have a non-trivial
          # amount of other caches: https://github.com/actions/stale/issues/1136
          # so, operations-per-run is large enough to hopefully process all
          # of the open issues/pr's in the repo.
          operations-per-run: 300
          exempt-all-milestones: true
          stale-pr-message: "This PR is stale because it has been open 3 months with no activity. Remove stale label or comment or this will be closed in 3 months."
          close-pr-message: "This PR was closed because it has been stalled for 3 months with no activity."
          days-before-pr-stale: 90
          days-before-pr-close: 90
          stale-issue-message: "This issue is stale because it has been open 6 months with no activity. Remove stale label or comment or this will be closed in 3 months."
          close-issue-message: "This issue was closed because it has been stalled for 3 months with no activity."
          days-before-issue-stale: 180
          days-before-issue-close: 90
